import { createElement } from 'lwc';
import UserPermissionBasedOnUI_EP_23 from 'c/userPermissionBasedOnUI_EP_23';

describe('c-user-permission-based-on-u-i-e-p-23', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-user-permission-based-on-u-i-e-p-23', {
            is: UserPermissionBasedOnUI_EP_23
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});