public class demo1  implements interfacedemo {
       public string name ;
       public integer age ;
       public date dob ;
       public demo1 () {
        name = 'chinnna';
        age = 33;
        dob = date.newInstance(2022, 04, 14);      
          
    }
    public integer numbersssss(){
            return   45;
        
           }
        public void demomethod () {
              system.debug('varibles ......'+name);
    }
}