public class functions {
    
    integer num1= 45;
    integer num2 = 45;
    public integer substraction (integer num1 , integer num2){
        system.debug ('substration results ....'+(num1-num2));
        integer num3 = num1 - num2;
        return num3;
        
    }
    public integer  mutiplication (){
        system.debug('multiplication '+(num1*num2));
        integer num3 = num1 * num2;
        return num3;
        
    }
}