public class pratice1 {
    decimal dd;
    string name;
    boolean b;
    public void methoddemo(){
        b =true;
     
        system.debug('b===='+b);
           dd=2.3456;
        integer int1 =1;
        double bb=233.3333;
        date todaydate= system.today();
       
        date bday =date.newInstance(2028, 11, 25);
        system.debug('decimal.......'+dd);
        system.debug('integer.......'+int1);
        system.debug('double.......'+bb);
         system.debug('date.......'+todaydate);
        system.debug('date.......'+bday);
        //pratice22.method2();
    }
   

}